### Users
  POST http://localhost:8000/users
Content-Type: application/json

{
  "name": "Teste",
  "email": "test@example.com",
  "password": "Teste123?",
  "role": "TEACHER"
}
###
GET http://localhost:8000/users
###
GET http://localhost:8000/users/cmanuylv30001gd3wkbabxm4e
###
DELETE http://localhost:8000/users/cmanuylv30001gd3wkbabxm4e
###
PATCH http://localhost:8000/users/cmanuylv30001gd3wkbabxm4e
Content-Type: application/json

{
  "name": "Teste",
  "email": "test@example.com",
    "password": "Teste1234?"
}

### Schools
GET http://localhost:8000/schools?page=1&pageSize=10
###
GET http://localhost:8000/schools/cmahci71t0000gd29axi4yk1k
###
PATCH localhost:8000/schools/cmahci71t0000gd29axi4yk1k
Content-Type: application/json

{
  "uf": "RO"
}