### Users
  POST http://localhost:8000/users
Content-Type: application/json

{
  "name": "Teste",
  "email": "test@example.com",
  "password": "Teste123?",
  "role": "TEACHER",
  "cpf": "12345678901"
}
###
GET http://localhost:8000/users
###
GET http://localhost:8000/users/cma5zoonp0000gd1zrkvwxgah
###
DELETE http://localhost:8000/users/cma6ymu4e0000gd0khposiflb
###