packages:
  - apps/*
  - packages/*
  - libs/*
onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - '@scarf/scarf'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - argon2
  - prisma
  - sharp
  - unrs-resolver
