export enum Servicerestriction {
  'ESCOLA ATENDE EXCLUSIVAMENTE ALUNOS COM DEFICIÊNCIA' = 'ESCOLA ATENDE EXCLUSIVAMENTE ALUNOS COM DEFICIÊNCIA',
  'ESCOLA EM FUNCIONAMENTO E SEM RESTRIÇÃO DE ATENDIMENTO' = 'ESCOLA EM FUNCIONAMENTO E SEM RESTRIÇÃO DE ATENDIMENTO',
  'ESCOLA EXCLUSIVA DE ATENDIMENTO EDUCACIONAL ESPECIALIZADO' = 'ESCOLA EXCLUSIVA DE ATENDIMENTO EDUCACIONAL ESPECIALIZADO',
  'ESCOLA EXCLUSIVA DE ATIVIDADE COMPLEMENTAR' = 'ESCOLA EXCLUSIVA DE ATIVIDADE COMPLEMENTAR',
  'ESCOLA PARALISADA' = 'ESCOLA PARALISADA',
}
